# Generated by Django 6.1 on 2026-08-18 10:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pannes', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='categorie',
            old_name='nom_categorie',
            new_name='nom',
        ),
        migrations.RenameField(
            model_name='equipement',
            old_name='nom_equipement',
            new_name='nom',
        ),
        migrations.RenameField(
            model_name='intervention',
            old_name='description_action',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='panne',
            old_name='date_creation',
            new_name='date_signalement',
        ),
        migrations.RenameField(
            model_name='service',
            old_name='nom_service',
            new_name='nom',
        ),
        migrations.RemoveField(
            model_name='equipement',
            name='code_inventaire',
        ),
        migrations.RemoveField(
            model_name='panne',
            name='categorie',
        ),
        migrations.RemoveField(
            model_name='panne',
            name='code_ticket',
        ),
        migrations.RemoveField(
            model_name='panne',
            name='demandeur',
        ),
        migrations.RemoveField(
            model_name='panne',
            name='technicien',
        ),
        migrations.RemoveField(
            model_name='panne',
            name='titre',
        ),
        migrations.RemoveField(
            model_name='service',
            name='site',
        ),
        migrations.AddField(
            model_name='equipement',
            name='categorie',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pannes.categorie'),
        ),
        migrations.AddField(
            model_name='equipement',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='panne',
            name='signale_par',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pannes_signalees', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='service',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='equipement',
            name='service',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pannes.service'),
        ),
        migrations.AlterField(
            model_name='intervention',
            name='panne',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interventions', to='pannes.panne'),
        ),
        migrations.AlterField(
            model_name='panne',
            name='equipement',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='pannes', to='pannes.equipement'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='panne',
            name='statut',
            field=models.CharField(choices=[('signalement', 'Signalée'), ('en_cours', 'En cours de réparation'), ('resolue', 'Résolue')], default='signalement', max_length=20),
        ),
        migrations.AlterField(
            model_name='utilisateur',
            name='role',
            field=models.CharField(choices=[('admin', 'Administrateur'), ('agent', 'Agent de maintenance')], default='agent', max_length=20),
        ),
    ]
